libraries:
	cd trie;make
	cd util;make
maxchain:
	cd apps;make maxchain
subwords:
	cd apps;make subwords 
cleanobj:
	cd trie;rm  trie.o
	cd util;rm dictload.o dictutils.o
cleanlib:
	cd trie;rm libtrie.so
	cd util;rm libwordutils.so
cleanout:
	cd apps;rm a.out